config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { passwords: "users/passwords", registrations: 'users/registrations' } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "przykladowe_trasy", to: "tours#index", as: "tours"
  get "przykladowa_trasa_nr_:id", to: "tours#show", as: "tour"
  get "moje_trasy", to: "tours#my", as: "my_tours"
  get "moja_trasa_nr_:id", to: "tours#my_show", as: "my_tour"
  delete 'przykladowa_trasa_nr_:id' => 'tours#destroy'
  get "tours/add_to_my_tours/:id", to: "tours#add_to_my_tours", as: "add_to_my_tours"

  get "oferowane_znizki", to: "discounts#index", as: "discounts"

  get "nasi_przewodnicy", to: "guides#index", as: "guides"

  get "atrakcje", to: "attractions#index", as: "attractions"
  get "atrakcja_nr_:id", to: "attractions#show", as: "attraction"

  post "cart/add_to_cart/:id", to: "cart#add_to_cart", as: "add_to_cart"
  get "cart/remove_from_cart/:id", to: "cart#remove_from_cart", as: "remove_from_cart"
  get "cart", to: "cart#index"
  post '/cart' => 'cart#create'

  root :to => "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :guide, optional: true
  belongs_to :discount, optional: true
  has_and_belongs_to_many :attractions
  belongs_to :attraction_start, :class_name => "Attraction"
  belongs_to :attraction_end, :class_name => "Attraction"
  has_and_belongs_to_many :users
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: %i[ show edit update destroy ]
  before_action :set_my_tour, only: %i[ my_show ]
  # GET /tours or /tours.json
  def index
    @tours = Tour.find(1,2,3,4)
  end

  def my
    @tours = current_user.tours
  end

  def my_show
    respond_to do |format|
      format.html
      format.pdf do
        instructions = params[:instruction]
        instructions = instructions.to_s.gsub(/<br>/, "|")
        instructions = instructions.gsub(/<b>/, " ")
        instructions = instructions.gsub(/<\/b>/, " ")
        instructions = instructions.gsub(/<div style="font-size:0.9em">/, "")
        instructions = instructions.gsub(/<\/div>\. Segment/, "\n\n\nSegment")
        instructions = instructions.gsub(/<\/div>/, ". ")
        instructions = instructions.gsub(/<wbr\/>/, " ")
        time = params[:total_t]
        distance = params[:total_d] 
        pdf = PdfGenerator.new(current_user.tours.find(params[:id]),instructions,time, distance)
        send_data pdf.render, type: "application/pdf",
                 disposition: "inline" ,
                  filename: "Wycieczka"

      end
    end
  end

  def add_to_my_tours
    @id=Tour.find(params[:id])
    current_user.tours << @id unless current_user.tours.include?(@id)
    redirect_to root_path, notice: "Trasa została dodana do Twojego konta"
  end

  # GET /tours/1 or /tours/1.json
  def show
  end


  # DELETE /tours/1 or /tours/1.json
  def destroy
    if [1,2,3,4].include? @tour.id
      current_user.tours.destroy(@tour.id)

      respond_to do |format|
      format.html { redirect_to root_path, notice: "Trasa usunięta z Twojego panelu." }
      end

    else
      @tour.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Trasa usunięta z Twojego panelu." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    def set_my_tour
      @tour = current_user.tours.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tour_params
      params.require(:tour).permit(:guide_id, :attraction_start_id, :attraction_end_id, {attraction_ids: []},:instruction, :discount_id, :information, :total_d, :total_t)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/index.html.erb
<!DOCTYPE html>
<html>

<%= stylesheet_link_tag "application", "tours"%>

<p id="notice"><%= notice %></p>

<h1 class="header">Przykładowe trasy</h1>
<p>Brak pomysłu na wycieczkę?</p>
<p>Skorzystaj z proponowanych tras:</p>
<br>

<body>
  <% @tours.each do |tour| %>
      <button type="button" class="collapsible-header">Trasa #<%= tour.id %></button>
      <div class="collapsible-content">
        <h3>Atrakcja początkowa: </h3>
        <%= link_to Attraction.find(tour.attraction_start_id), class: "hyperlink" do %> <%=Attraction.find(tour.attraction_start_id).name%> <%end %>
        <h3>Atrakcje poboczne:</h3>
          <ol>
            <% tour.attractions.each do |attraction| %>
              <li>
                <%= link_to attraction, class: "hyperlink" do %>
                <%= attraction.name %>
              </li>
              <%end %>
            <%end %>
          </ol>
          <h3>Atrakcja końcowa: </h3> 
          <%= link_to Attraction.find(tour.attraction_end_id), class: "hyperlink" do %> <%=Attraction.find(tour.attraction_end_id).name%>  <%end %>
          <h3>Koszt trasy za bilety:<%= tour.sumcosts %> zł</h3> 
          <%= link_to "Zobacz dokładny plan trasy", tour ,class:"btn btn-success"%></p>

        <table>
          <% if current_user %>
            <%# else %> <!--remove_from_cart_path(attraction), method: :delete,-->
            <td> <% if !current_user.tours.include? tour%>
  <%= link_to "Dodaj do swoich tras",add_to_my_tours_path(tour.id), class:"btn btn-success" %>
  <% end%> <td>
            <%# end %> <!-- add_to_cart_path(attraction),-->
            <%# if current_user. include?(tour) %> <!--TODO: Dodaj trasę do konta. Ewentualnie zastapienie koszyka po zapytaniu jesli jest jakas zawartosc-->
<!--            <td> <%#= button_to "Usuń z koszyka", class:"btn btn-danger"%> <td>-->
          <% end %>
        </table>
        <br>
      </div>

  <%end %>
  <br>
</body>

  <script>
      var coll = document.getElementsByClassName("collapsible-header");
      var i;

      for (i = 0; i < coll.length; i++) {
          coll[i].addEventListener("click", function() {
              this.classList.toggle("active");
              var content = this.nextElementSibling;
              if (content.style.display === "block") {
                  content.style.display = "none";
              } else {
                  content.style.display = "block";
              }
          });
      }
  </script>

<script>
      $(document).ready(function () { $('.data-toggle').collapse();});
  </script>

</html>

app/views/tours/my.html.erb
<%= stylesheet_link_tag "application", "tours"%>

<h1 class="header">Moje trasy</h1>

<% if @tours.empty?%>
  <p>Nie utworzono jeszcze trasy</p>
<% else %>
  <% @tours.each do |tour|%>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="colgroup">#</th>
        <th scope="colgroup">Przebieg trasy</th>
        <th scope="colgroup">Koszt trasy</th>
      </tr>
      <colgroup>
        <col style="width:5%">
        <col style="width:75%">
        <col style="width:10%">
        <col style="width:10%">
      </colgroup>
    </thead>
    <tbody>
    <% @sum_costs = 0 %>
    <% @start_attraction = Attraction.find(tour.attraction_start_id)%>
    <% @end_attraction = Attraction.find(tour.attraction_end_id)%>
    <% @sum_costs += @start_attraction.price + @end_attraction.price %>
      <tr>
        <th scope="row"><%= tour.id %></th>
          <td>
              <table class="table">
                  <thead class="thead-dark">
                      <tr>
                      <th scope="colgroup">Atrakcja początkowa</th>
                      <th scope="colgroup">Ciąg atrakcji</th>
                      <th scope="colgroup">Atrakcja końcowa</th>
                      </tr>
                  <colgroup>
                    <col style="width:15%">
                    <col style="width:70%">
                    <col style="width:15%">
                  </colgroup>
                  </thead>
                      <tbody>
                          <tr>
                              <td> <%= @start_attraction.name %> </td>
                              <td> -->
                              <% tour.attractions.each do |attraction| %>
                              <%= attraction.name %> -->
                              <% @sum_costs += attraction.price%>
                              <% end %>
                              </td>
                              <td> <%= @end_attraction.name %> </td>
                          </tr>
                      </tbody>
              </table>
          </td>
          <td><%= @sum_costs%></td>
          <td><%= link_to 'Pokaż', my_tour_path(tour.id), class:"btn btn-info"%></td>
      </tr>
    </tbody>
  </table>
  <%end%>
<%end%>

app/views/tours/my_show.html.erb
<%= stylesheet_link_tag "application", "tours"%>

<script>
      function initMap() {
        const directionsService = new google.maps.DirectionsService();
        const directionsRenderer = new google.maps.DirectionsRenderer();
        const map = new google.maps.Map(document.getElementById("map"), {
          zoom: 6,
          center: { lat: 41.85, lng: -87.65 },
        });
        directionsRenderer.setMap(map);
        window.onload = calculateAndDisplayRoute(directionsService, directionsRenderer);
      }

      function calculateAndDisplayRoute(directionsService, directionsRenderer) {
        const waypts = [];
        <% @waypoints_attraction = Attraction.where(id: @tour.attraction_ids) %>
        <% @start_attraction = Attraction.find(@tour.attraction_start_id)%>
        <% @end_attraction = Attraction.find(@tour.attraction_end_id)%>
        <% @waypoints_attraction.each do |attraction| %>
            waypts.push({
              location: new google.maps.LatLng(<%= attraction.x %>,<%= attraction.y %>),
              stopover: true,
            });
            <%end%>
        directionsService.route(
          {
            origin: "<%= @start_attraction.name %>",
            destination: "<%= @end_attraction.name %>",
            waypoints: waypts,
            optimizeWaypoints: true,
            travelMode: google.maps.TravelMode.WALKING,
            avoidTolls: true,
          },
          (response, status) => {
            if (status === "OK" && response) {
              directionsRenderer.setDirections(response);
              console.log(response);
              const route = response.routes[0];
              const summaryPanel = document.getElementById("directions-panel");
              let summaryToPDF = "";
              summaryPanel.innerHTML = "";
              let total_distance = 0;
              let total_time = 0;
              // For each route, display summary information.
              summaryPanel.innerHTML += "Start:"
              for (let i = 0; i < route.legs.length; i++) {
                  const routeSegment = i + 1;
                    summaryPanel.innerHTML +=
                    "<b> Segment: " + routeSegment + "</b><br> Instrukcja dotarcia: <br>";
                    summaryToPDF += "Segment: " + routeSegment + " Instrukcja dotarcia: \n\n";
                    summaryToPDF += route.legs[i].start_address + " do ";
                    summaryPanel.innerHTML += route.legs[i].start_address + " do ";
                    summaryPanel.innerHTML += route.legs[i].end_address + "<br>";
                    summaryToPDF += route.legs[i].end_address + "\n\n";
                    
                  for( let j = 0; j < route.legs[i].steps.length; j++){
                    summaryPanel.innerHTML += route.legs[i].steps[j].instructions+ ". ";
                    summaryToPDF += route.legs[i].steps[j].instructions+ ". ";
                    total_distance += route.legs[i].steps[j].distance.value;
                    total_time += route.legs[i].steps[j].duration.value;
                  }
                summaryPanel.innerHTML += "<br>";
                summaryToPDF += "\n";
                  route.legs[i].distance.text + "<br><br><br>";
                
              }
              document.getElementById("total_durations").innerHTML= "Długość trasy: "+ total_distance/1000 + "km.";
           
              total_time += <%= @tour.totaltime %>
              document.getElementById("total_time").innerHTML="Przybliżony czas przejścia: " + Math.round(total_time/60 ) +"min.";
              document.getElementById("instruction").value=summaryToPDF;
              document.getElementById("total_t").value="Przybliżony czas przejścia: " + Math.round(total_time/60 ) +"min.";
                 document.getElementById("total_d").value= "Długość trasy: "+ total_distance/1000 + "km.";
            } 
            else {
              window.alert("Directions request failed due to " + status);
            }
          }
        );
      }
    </script>
<h1 align="center"> 
Plan trasy:
</h1>
<div class="container">
<div id="left" style="width:50%;min-height:800px;float:left;padding-right:50px">
<% @sum_costs = 0 %>
<% @start_attraction = Attraction.find(@tour.attraction_start_id)%>
<% @end_attraction = Attraction.find(@tour.attraction_end_id)%>
<br/>
<h2>
Atrakcje do obejrzenia podczas trasy:
</h2>
<% if @start_attraction == @end_attraction%>
Atrakcja, z której zaczynasz i kończysz trasę: <%= @start_attraction.name%> <br/>
<% else%>
Atrakcja, z której zaczynasz trasę: <%= @start_attraction.name%> <br/><strong> Opłata: </strong> <%=  @start_attraction.price %> zł<br/>
Atrakcja, na której kończysz trasę: <%= @end_attraction.name%><strong> Opłata: </strong> <%= @end_attraction.price %> zł<br/>
<% end %>
<% @tour.attractions.each do |attraction| %>
  <h4>
  <%= attraction.name %> : 
  </h4>
        <div class="accordion-body">
          <strong> Opłata: </strong> <%= attraction.price %> zł<br/>
          <strong> Czas zwiedzania:</strong> <%= attraction.sightseeing_time %> minut<br/>
        </div>
 <% end %>
<p>

  <% if !@tour.guide_id.nil?%>
    <% @guide = Guide.find(@tour.guide_id) %>
    <strong>Przewodnik trasy:</strong>
    <%= @guide.name_and_surname %>
    <strong> Telefon kontaktowy: </strong>
    <%= @guide.telnumber %>
  <% end %>
  <div class="information">
  <h3> INFORMACJE DOTYCZĄCE TRASY </h3>
  Całkowita opłata za podróż: <%= @tour.sumcosts%> zł.
   <% if @tour.discount_id%>
    Całkowita opłata ze zniżką: <%= @tour.sumcosts - (@tour.sumcosts * (Discount.find(@tour.discount_id).percent)/100).round(2)%> zł.
  <%end%>

  <div id="total_durations"> </div>
  <div id="total_time"> </div>
  <%= form_with url: my_tour_path(format: :pdf), method: :get do |form| %>
  <%= form.hidden_field :instruction %>
  <%= form.hidden_field :total_d %>
  <%= form.hidden_field :total_t %>
  <%= form.submit "Wygeneruj PDF", class: "btn btn-success"%>
<% end %>

<%= button_to 'Usuń trasę',@tour, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</p>
</div>

<div id="right" style="width:50%;float:left;">
<h2> Mapa i trasa przejścia </h2>
<div id="map" style="width:100%;min-height:800px;"></div>
<script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7vOoTEHKZlV89hsFiNdshzf74UMM_dnk&callback=initMap&libraries=&v=weekly"
      async
    ></script>
<script>
var left=document.getElementById('left').style.height;
 document.getElementById('map').style.height=left;
</script> 
</div>
</div>
<h2> Instrukcja przejścia </h2>
<div id="directions-panel"> </div>  
</div>

app/views/tours/show.html.erb
<%= stylesheet_link_tag "application", "tours"%>

<script>
      function initMap() {
        const directionsService = new google.maps.DirectionsService();
        const directionsRenderer = new google.maps.DirectionsRenderer();
        const map = new google.maps.Map(document.getElementById("map"), {
          zoom: 6,
          center: { lat: 41.85, lng: -87.65 },
        });
        directionsRenderer.setMap(map);
        window.onload = calculateAndDisplayRoute(directionsService, directionsRenderer);
      }

      function calculateAndDisplayRoute(directionsService, directionsRenderer) {
        const waypts = [];
        <% @waypoints_attraction = Attraction.where(id: @tour.attraction_ids) %>
        <% @start_attraction = Attraction.find(@tour.attraction_start_id)%>
        <% @end_attraction = Attraction.find(@tour.attraction_end_id)%>
        <% @waypoints_attraction.each do |attraction| %>
            waypts.push({
              location: new google.maps.LatLng(<%= attraction.x %>,<%= attraction.y %>),
              stopover: true,
            });
            <%end%>
        directionsService.route(
          {
            origin: "<%= @start_attraction.name %>",
            destination: "<%= @end_attraction.name %>",
            waypoints: waypts,
            optimizeWaypoints: true,
            travelMode: google.maps.TravelMode.WALKING,
            avoidTolls: true,
          },
          (response, status) => {
            if (status === "OK" && response) {
              directionsRenderer.setDirections(response);
              console.log(response);
              const route = response.routes[0];
              const summaryPanel = document.getElementById("directions-panel");
              let summaryToPDF = "";
              summaryPanel.innerHTML = "";
              let total_distance = 0;
              let total_time = 0;
              // For each route, display summary information.
              summaryPanel.innerHTML += "Start:"
              for (let i = 0; i < route.legs.length; i++) {
                  const routeSegment = i + 1;
                    summaryPanel.innerHTML +=
                    "<b> Segment: " + routeSegment + "</b><br> Instrukcja dotarcia: <br>";
                    summaryToPDF += "Segment: " + routeSegment + " Instrukcja dotarcia: \n\n";
                    summaryToPDF += route.legs[i].start_address + " do ";
                    summaryPanel.innerHTML += route.legs[i].start_address + " do ";
                    summaryPanel.innerHTML += route.legs[i].end_address + "<br>";
                    summaryToPDF += route.legs[i].end_address + "\n\n";
                    
                  for( let j = 0; j < route.legs[i].steps.length; j++){
                    summaryPanel.innerHTML += route.legs[i].steps[j].instructions+ ". ";
                    summaryToPDF += route.legs[i].steps[j].instructions+ ". ";
                    total_distance += route.legs[i].steps[j].distance.value;
                    total_time += route.legs[i].steps[j].duration.value;
                  }
                summaryPanel.innerHTML += "<br>";
                summaryToPDF += "\n";
                  route.legs[i].distance.text + "<br><br><br>";
                
              }
              document.getElementById("total_durations").innerHTML= "Długość trasy: "+ total_distance/1000 + "km.";
           
              total_time += <%= @tour.totaltime %>
              document.getElementById("total_time").innerHTML="Przybliżony czas przejścia: " + Math.round(total_time/60 ) +"min.";
              document.getElementById("instruction").value=summaryToPDF;
              document.getElementById("total_t").value="Przybliżony czas przejścia: " + Math.round(total_time/60 ) +"min.";
                 document.getElementById("total_d").value= "Długość trasy: "+ total_distance/1000 + "km.";
            } 
            else {
              window.alert("Directions request failed due to " + status);
            }
          }
        );
      }
    </script>
<h1 align="center"> 
Plan trasy:
</h1>
<div class="container">
<div id="left" style="width:50%;min-height:800px;float:left;padding-right:50px">
<% @sum_costs = 0 %>
<% @start_attraction = Attraction.find(@tour.attraction_start_id)%>
<% @end_attraction = Attraction.find(@tour.attraction_end_id)%>
<br/>
<h2>
Atrakcje do obejrzenia podczas trasy:
</h2>
<% if @start_attraction.name == @end_attraction.name %>
Atrakcja, z której zaczynasz i kończysz trasę: <%= @start_attraction.name%>  <strong> Opłata: </strong> <%= @start_attraction.price %> zł<br/> <br/>
<% else%>
Atrakcja, z której zaczynasz trasę: <%= @start_attraction.name%> <strong> Opłata: </strong> <%= @start_attraction.price %> zł<br/>
Atrakcja, na której kończysz trasę: <%= @end_attraction.name%> <strong> Opłata: </strong> <%= @end_attraction.price %> zł<br/><br/>
<% end %>
<% @tour.attractions.each do |attraction| %>
  <h4>
  <%= attraction.name %> : 
  </h4>
        <div class="accordion-body">
          <strong> Opłata: </strong> <%= attraction.price %> zł<br/>
          <strong> Czas zwiedzania:</strong> <%= attraction.sightseeing_time %> minut<br/>
        </div>
 <% end %>
<p>

  <% if !@tour.guide_id.nil?%>
    <% @guide = Guide.find(@tour.guide_id) %>
    <strong>Przewodnik trasy:</strong>
    <%= @guide.name_and_surname %>
    <strong> Telefon kontaktowy: </strong>
    <%= @guide.telnumber %>
  <% end %>
  <div class="information">
  <h3> INFORMACJE DOTYCZĄCE TRASY </h3>
  Całkowita opłata za podróż: <%= @tour.sumcosts%> zł.
   <% if @tour.discount_id%>
    Całkowita opłata ze zniżką: <%= @tour.sumcosts - (@tour.sumcosts * (Discount.find(@tour.discount_id).percent)/100).round(2)%> zł.
  <%end%>

  <div id="total_durations"> </div>
  <div id="total_time"> </div>
  <% if current_user %>
  <% if !current_user.tours.include? @tour%>
  <%= link_to "Dodaj do swoich tras",add_to_my_tours_path(@tour.id), class:"btn btn-success" %>
  <% end%>
  <% end%>
  </div>
</p>
</div>

<div id="right" style="width:50%;float:left;">
<h2> Mapa i trasa przejścia </h2>
<div id="map" style="width:100%;min-height:800px;"></div>
<script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7vOoTEHKZlV89hsFiNdshzf74UMM_dnk&callback=initMap&libraries=&v=weekly"
      async
    ></script>
<script>
var left=document.getElementById('left').style.height;
 document.getElementById('map').style.height=left;
</script> 
</div>
</div>
<h2> Instrukcja przejścia </h2>
<div id="directions-panel"> </div>  
</div>