config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { passwords: "users/passwords", registrations: 'users/registrations' } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "przykladowe_trasy", to: "tours#index", as: "tours"
  get "przykladowa_trasa_nr_:id", to: "tours#show", as: "tour"
  get "moje_trasy", to: "tours#my", as: "my_tours"
  get "moja_trasa_nr_:id", to: "tours#my_show", as: "my_tour"
  delete 'przykladowa_trasa_nr_:id' => 'tours#destroy'
  get "tours/add_to_my_tours/:id", to: "tours#add_to_my_tours", as: "add_to_my_tours"

  get "oferowane_znizki", to: "discounts#index", as: "discounts"

  get "nasi_przewodnicy", to: "guides#index", as: "guides"

  get "atrakcje", to: "attractions#index", as: "attractions"
  get "atrakcja_nr_:id", to: "attractions#show", as: "attraction"

  post "cart/add_to_cart/:id", to: "cart#add_to_cart", as: "add_to_cart"
  get "cart/remove_from_cart/:id", to: "cart#remove_from_cart", as: "remove_from_cart"
  get "cart", to: "cart#index"
  post '/cart' => 'cart#create'

  root :to => "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/discount.rb
class Discount < ApplicationRecord
  validates :name, presence: true
  validates :percent, presence: true
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  def index
    @discounts = Discount.all
  end
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/views/discounts/index.html.erb
<!DOCTYPE html>
<html>

<%= stylesheet_link_tag "application", "discounts"%>

<p id="notice"><%= notice %></p>

<h1 class="header">Zapłać mniej za bilety</h1>
<p>
  Dzięki współpracy z firmami turystycznymi oferujemy naszym klientom następujące zniżki,
  pozwalające zaoszczędzić na biletach:
</p>
<br>

<body>
  <% @discounts.each do |discount| %>
    <div class="list-item">
      <div class="list-left"><%= discount.name %></div>
      <div class="list-right"><%= discount.percent %>%</div>
    </div>
    <br>
  <%end %>
</body>

</html>

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Nazwa zniżki</th>-->
<!--      <th>Procent</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
    <%# @discounts.each do |discount| %>
<!--      <tr>-->
<!--        <td><%#= discount.name %></td>-->
<!--        <td><%#= discount.percent %> % </td>-->
<!--        <td><%#= link_to 'Show', discount %></td>-->
<!--        <td><%#= link_to 'Edit', edit_discount_path(discount) %></td>-->
<!--        <td><%#= link_to 'Destroy', discount, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
    <%# end %>
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<%#= link_to 'New Discount', new_discount_path %>
<%#= link_to 'Powrót do strony głównej', root_path %>