config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { passwords: "users/passwords", registrations: 'users/registrations' } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "przykladowe_trasy", to: "tours#index", as: "tours"
  get "przykladowa_trasa_nr_:id", to: "tours#show", as: "tour"
  get "moje_trasy", to: "tours#my", as: "my_tours"
  get "moja_trasa_nr_:id", to: "tours#my_show", as: "my_tour"
  delete 'przykladowa_trasa_nr_:id' => 'tours#destroy'
  get "tours/add_to_my_tours/:id", to: "tours#add_to_my_tours", as: "add_to_my_tours"

  get "oferowane_znizki", to: "discounts#index", as: "discounts"

  get "nasi_przewodnicy", to: "guides#index", as: "guides"

  get "atrakcje", to: "attractions#index", as: "attractions"
  get "atrakcja_nr_:id", to: "attractions#show", as: "attraction"

  post "cart/add_to_cart/:id", to: "cart#add_to_cart", as: "add_to_cart"
  get "cart/remove_from_cart/:id", to: "cart#remove_from_cart", as: "remove_from_cart"
  get "cart", to: "cart#index"
  post '/cart' => 'cart#create'

  root :to => "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-center text-white">
  Kontakt email: <strong> bialystokroutes@gmail.com</strong><br><br>
  © 2021 Copyright: BialystokRoutes <i> All rights reserved. </i>
</footer>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="pl">

<%= stylesheet_link_tag "application"%>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/" style="margin: auto;">
    <%= image_tag("Logo.png", width: '50px') %>

<!--    <div class="header"></div>-->
    BiałystokRoutes
  </a>
  <div class="container-fluid" >
    <button style="margin: auto; width: 25%;" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="text-align: center">

<!--        <li class="nav-item" ><%#= link_to "My categories", categories_path, class:"nav-link active"%></li>-->
        <li class="nav-item" ><%= link_to "Dostępne atrakcje", attractions_path, class:"nav-link active"%></li>
        <li class="nav-item" ><%= link_to "Przewodnicy", guides_path , class:"nav-link active"%></li>
        <li class="nav-item" ><%= link_to "Zniżki", discounts_path, class:"nav-link active"%></li>
        <li class="nav-item" ><%= link_to "Przykładowe trasy", tours_path, class:"nav-link active"%></li>
        <%if current_user && current_user.admin%>
        <li class="nav-item" ><%= link_to "Panel administracyjny", rails_admin_path, class:"nav-link active text-danger"%></li>
        <% end %>
      </ul>
      
    </div>
    </div>
  </div>

   <% if current_user %>
        <%= link_to "Koszyk", cart_path, class:"btn btn-outline-success"%>
        <%= link_to "Trasy", my_tours_path,  class:"btn btn-outline-success"%>
        <%= button_to 'Wyloguj się', destroy_user_session_path, class:"btn btn-outline-success",
                                                          method: :delete %>
        </div>
      <% else %>

        <%= link_to 'Zaloguj się', new_user_session_path, class:"btn btn-outline-success" %>
      
      <%end%>

</nav>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>BialystokRoutes</title>
  <%= favicon_link_tag asset_path('Logo.png') %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %> 
  <%= csp_meta_tag %>

  <link rel="shortcut icon" type="image/png" href="/favicon.png"/>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  <!-- Mapy -->
  <script src="//maps.google.com/maps/api/js?key=AIzaSyA7vOoTEHKZlV89hsFiNdshzf74UMM_dnk"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>
  <script src='//cdn.jsdelivr.net/gmaps4rails/2.1.2/gmaps4rails.js'> </script>
  <script src='//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js'> </script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"> 
  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header'%>
<div class="container-md" style="min-height:80vh;">
  <%= render 'layouts/alerts'%>
  <%= yield %>
</div>
  <%= render 'layouts/footer'%>
</body>
</html>