config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { passwords: "users/passwords", registrations: 'users/registrations' } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "przykladowe_trasy", to: "tours#index", as: "tours"
  get "przykladowa_trasa_nr_:id", to: "tours#show", as: "tour"
  get "moje_trasy", to: "tours#my", as: "my_tours"
  get "moja_trasa_nr_:id", to: "tours#my_show", as: "my_tour"
  delete 'przykladowa_trasa_nr_:id' => 'tours#destroy'
  get "tours/add_to_my_tours/:id", to: "tours#add_to_my_tours", as: "add_to_my_tours"

  get "oferowane_znizki", to: "discounts#index", as: "discounts"

  get "nasi_przewodnicy", to: "guides#index", as: "guides"

  get "atrakcje", to: "attractions#index", as: "attractions"
  get "atrakcja_nr_:id", to: "attractions#show", as: "attraction"

  post "cart/add_to_cart/:id", to: "cart#add_to_cart", as: "add_to_cart"
  get "cart/remove_from_cart/:id", to: "cart#remove_from_cart", as: "remove_from_cart"
  get "cart", to: "cart#index"
  post '/cart' => 'cart#create'

  root :to => "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: %i[ show ]

  # GET /attractions or /attractions.json
  def index
    # @attractions = Attraction.all
    @attractions = Attraction.page(params[:page]).per(4)
  end

  # GET /attractions/1 or /attractions/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attraction_params
      params.require(:attraction).permit(:name, :x, :y, :price, :description, :sightseeing_time, {category_ids: []}, :image)
    end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/index.html.erb
<!DOCTYPE html>
<html>

<%= stylesheet_link_tag "application", "attractions"%>

<p id="notice"><%= notice %></p>

<h1 class="header"> Wybierz atrakcje</h1>
<p>
  Oto oferowane przez nas atrakcje w Białymstoku i okolicy. Możesz się z nimi zapoznać
  klikając na odpowiedni panel, lub dodać do koszyka.
</p>

<body>

<div class="container">

<% @attractions.each do |attraction| %>

    <%= link_to attraction, class: "hyperlink" do %>

    <% if attraction.image.blank? %>

         <div class="item">

    <% else %>

        <div class="item bg-img" style="background-image:url(<%= rails_blob_url(attraction.image); %>);width: 100%;
        height: 100%;
        @include background-image();">

    <% end %>
    
    <h4 class="title"><%= attraction.name %></h4>

    <div class="parent">

      <div class="hidden-child">
        <br>
        <p><% if attraction.price > 0%>
          <strong>Opłata:</strong>
          <%= attraction.price %> zł
        <%else %>
          <strong>Obiekt bezpłatny</strong>
        <%end %></p>
        <p>Czas zwiedzania: ok. <%= (attraction.sightseeing_time / 60.0).round(2) %> h</p>
        <p><% attraction.categories.each do |category| %>
            <%= category.name %>
          <% end %>
        </p>
      </div>

      <div class="hidden-child">
        <% if current_user %>
          <% if @cart.include?(attraction) %>
            <%= button_to "Usuń z koszyka", remove_from_cart_path(attraction), method: :get, class:"btn btn-danger" %>
          <% else %>
            <%= button_to "Dodaj do koszyka", add_to_cart_path(attraction), class:"btn btn-success" %>
          <% end %>
        <% end %>
      </div>

    </div>
    </div>
      <% end %>
<% end %>
</div>

<br>
<div class="paginate">
  <%= paginate @attractions %>
</div>

</body>
<br>

</html>

app/views/attractions/show.html.erb
<!DOCTYPE html>
<html>

<%= stylesheet_link_tag "application", "attractions"%>

<p id="notice"><%= notice %></p>

  <h1 class="header"><%= @attraction.name %></h1>

<body >
  <div>
  <div style="width:50%;float:left">
  <% if !@attraction.image.blank? %>
    <%= image_tag(@attraction.image, height:600, width:600) %>
    <br><br>
  <% end %>

  </div>
  <div style="width:50%;float:left">
  <p style="text-align: justify;"><strong>Opis atrakcji:</strong><%= @attraction.description %></p>
   <p style="text-align: justify;clear:both">
    <% if @attraction.price > 0%>
      <strong>Opłata:</strong>
      <%= @attraction.price %>
    <%else %>
      <strong>Wstęp bezpłatny!</strong>
    <%end %>

  </p>
  <p style="text-align: justify;">
    <strong>Czas zwiedzania:</strong>
    <%= @attraction.sightseeing_time %> min.
  </p>

  <p style="text-align: justify;">
    <strong>Kategorie:</strong>

        <% @attraction.categories.each do |category| %>
<%= category.name %> <br/>
        <%end %>

  </p>
  </div>
  </div>
 <h3 style="clear:both">Lokalizacja na mapie </h3>
  <div id="map"></div>
  <br>

</body>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7vOoTEHKZlV89hsFiNdshzf74UMM_dnk&callback=initMap&libraries=&v=weekly"
  async></script>

<script type="text/javascript">
    function initMap() {
        // The location of Uluru
        const uluru = { lat: <%= @attraction.x %>, lng: <%= @attraction.y %> };
        // The map, centered at Uluru
        const map = new google.maps.Map(document.getElementById("map"), {
            zoom: 16,
            center: uluru,
        });
        // The marker, positioned at Uluru
        const marker = new google.maps.Marker({
            position: uluru,
            map: map,
        });
    }
</script>


</html>